version: "3.8"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${DB}
      - MYSQL_ROOT_PASSWORD=${DBPASS}
    ports:
      - "3306:3306"
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db:/var/lib/mysql
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
volumes:
  db:
    driver: local
